name: torch-py39
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - blas=1.0
  - bleach=6.0.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-blosc2=2.7.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - chart-studio=1.1.0
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - colorspacious=1.1.2
  - contourpy=1.0.7
  - cryptography=38.0.4
  - cuda-cccl=12.1.109
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.1.105
  - cuda-runtime=11.8.0
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - darkdetect=0.8.0
  - dask-core=2023.3.1
  - dav1d=1.0.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dipy=1.6.0
  - double-conversion=3.2.0
  - edflib-python=1.0.6
  - eeglabio=0.0.2.post3
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.3.1
  - filelock=3.12.0
  - flit-core=3.8.0
  - fonttools=4.39.2
  - freetype=2.12.1
  - fsspec=2023.3.0
  - future=0.18.3
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glpk=5.0
  - h5io=0.1.7
  - h5netcdf=1.1.0
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icc_rt=2022.1.0
  - icu=68.2
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.26.0
  - imageio-ffmpeg=0.4.8
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipycanvas=0.13.1
  - ipyevents=2.0.1
  - ipykernel=6.15.0
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - ipyvtklink=0.2.3
  - ipywidgets=7.7.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsoncpp=1.9.4
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.5.0
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.39.1
  - locket=1.0.0
  - loguru=0.6.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mffpy=0.8.0
  - mistune=2.0.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mne=1.0.3
  - mne-base=1.0.3
  - mne-connectivity=0.5.0
  - mne-qt-browser=0.4.0
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.8.0
  - nest-asyncio=1.5.6
  - netcdf4=1.6.0
  - networkx=3.0
  - nibabel=5.0.1
  - nilearn=0.10.0
  - notebook=6.3.0
  - nptyping=2.5.0
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.5.0
  - openssl=1.1.1u
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=3.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.1.1
  - plotly=5.14.1
  - ply=3.11
  - pooch=1.7.0
  - proj=6.2.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pymatreader=0.0.30
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtgraph=0.12.4
  - pyqtwebengine=5.12.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-igraph=0.10.2
  - python-picard=0.7
  - python_abi=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyvista=0.38.5
  - pyvistaqt=0.9.1
  - pywavelets=1.4.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.1
  - qt=5.12.9
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.0
  - requests=2.28.2
  - retrying=1.3.3
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - scooby=0.7.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.7.7
  - six=1.16.0
  - snappy=1.1.10
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - suitesparse=5.4.0
  - sympy=1.12
  - tbb=2021.7.0
  - tenacity=8.2.2
  - terminado=0.15.0
  - texttable=1.6.7
  - threadpoolctl=3.1.0
  - tifffile=2023.3.21
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - typish=1.9.3
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - utfcpp=3.2.3
  - vc=14.2
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - vtk=9.0.3
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - wheel=0.38.4
  - widgetsnbextension=3.6.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.15.0
  - xarray=2023.2.0
  - xlrd=2.0.1
  - xlwt=1.3.0
  - xmltodict=0.13.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
      - torchaudio==2.0.2
      - torchvision==0.15.2